### ISSUE TITLE
Assertion Failed: No SVG found in production / staging

### ISSUE THREAD

**Issue by timiyay** [minutebase/ember-inline-svg#27]
`ember-inline-svg` is working well for me in development, but it fails when I deploy a staging or production build.

```
Assertion Failed: No SVG found for https://s3-ap-southeast-2.amazonaws.com/my-asset-bucket/assets/images/my_svg-ba344c0da7825ce242e302595e5122fe.svg
```

If I visit https://s3-ap-southeast-2.amazonaws.com/my-asset-bucket/assets/images/my_svg-ba344c0da7825ce242e302595e5122fe.svg, then the SVG is available.

I'm currently attempting to debug the issue. I've tried moving my SVGs to `public/assets/inline-svg`, and changing the `svg.paths` setting in `ember-cli-build.js`. However, `ember-inline-svg` seems to ignore this config, and looks for the image in `public/assets/images`.

I've worked through the checklist at https://github.com/minutebase/ember-inline-svg#no-svg-found--the-handlebars-template-is-not-rendered, but am still hitting the issue in staging / production.

**Comment by Duder-onomy** [comment]
I am having an identical issue, 

this library throws: 

```
Assertion Failed: No SVG found for ***
```

But when I visit that URL the svg is displayed correctly. 

@rlivsey Can you chime in and let us know next steps here? Maybe explain how this works under the hood so we can help debug it.

**Comment by Duder-onomy** [comment]
Ok, update from my end. 

I believe this library to be inlining the SVG into a file at build time, then looking the SVG up by path during runtime. 
On development builds everything works fine because the path in the template and the path in the built file are the same. Issues arise when you have paths changing, in my case, and I believe in @timiyay case above, we are using asset fingerprinting. The fingerprinting runs before the inline-ing, so the path it uses to lookup the file and the path it used to inline the svg into JS are different. 

I was able to solve this issue by ignoring the inlined svg's from my fingerprinting. 

```javascript
module.exports = function(defaults) {
  const app = new EmberApp(defaults, {
    fingerprint: {
     // ...
      exclude: ['assets/images/my-inlined-svg.svg'],
      extensions: ['js', 'css', 'png', 'jpg', 'gif', 'map', 'svg', 'ttf', 'woff'],
     // ...
    },
```

More info on ember-cli asset fingerprinting: 
https://ember-cli.com/asset-compilation#fingerprinting-and-cdn-urls

**Comment by timiyay** [comment]
Closing this issue as stale.
