### ISSUE TITLE
Passing a class to the inline-svg helper overwrites existing classes on the SVG element

### ISSUE THREAD

**Issue by istateside** [minutebase/ember-inline-svg#37]
Ran into this problem where I was setting a class within a template on an SVG (`concat "icon-" iconName`). Some of my SVGs have classes already on the element, and the applyClass utility overwrites those classes.

I threw together #36 as a quick solution. A similar solution could be used to set any attribute on the SVG, with a little more tweaking.

I noticed a conversation going on about componentizing the helper, so this may not be worth moving forward with. Figured I'd bring up the issue here. Would be happy to contribute towards this PR or componentizing in general.

**Comment by harrisjose** [comment]
I was initially hyped with the idea of componentizing, but coming to think of it I assume each component has instantiation and lifecycle costs which seem to be totally unnecessary here. 

As an aside, maybe we could convert the svg string to a DOM node so that we can set any attribute we want to it using `setAttribute()` ?? I tried this on my dev machine and it seems to be working well so far..
